NetworkPkg/Application: remove unused LineNo variable from NvmeOfCli
NetworkPkg/Application/NvmeOfCli/NvmeOfCli.c:648:33: error: variable
‘LineNo’ set but not used [-Werror=unused-but-set-variable=]
  648 |   UINTN                         LineNo        = 0;

      |                                 ^~~~~~
Signed-off-by: John Meneghini <jmeneghi@redhat.com>